#!/bin/sh
#
# 1. Do not introduce git submodules - we use subtree instead
# 2. Do not mix changes in a subtree and elsewhere in the same commit

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

if (git diff --cached --name-only HEAD | egrep "^\.gitmodules$" > /dev/null)
then
	echo "Error: Do not introduce git submodules - use git subtree instead."
	exit 1
fi

SUBTREE_FILES=$(git diff --cached --name-only HEAD | egrep "^\.clojure" | wc -l)
NON_SUBTREE_FILES=$(git diff --cached --name-only HEAD | egrep -v "^\.clojure" | wc -l)

echo "pre-commit: SUBTREE_FILES: $SUBTREE_FILES, NON_SUBTREE_FILES: $NON_SUBTREE_FILES"

if [ $SUBTREE_FILES -gt 0 ] && [ $NON_SUBTREE_FILES -gt 0 ]
then
	echo "Error: Do not mix changes in a subtree and elsewhere in the same commit."
	exit 1
fi

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
